### ISSUE TITLE
Tunneling unsuccessful

### ISSUE THREAD

**Issue by tuxayo** [vvviperrr/SimpleRT#57]
Hi :)

There is the VPN prompt in the phone. I have mobile network enabled. `curl example.org` works via adb. But as soon as I accept the prompt, curl freezes, no result.

With version 1.0 from F-Droid (could #37 cause an issue? #37)
PC counterpart : 20190906_9b63526-1

[cli.log.txt](https://github.com/vvviperrr/SimpleRT/files/6796226/cli.log.txt)
[ip-route.txt](https://github.com/vvviperrr/SimpleRT/files/6796228/ip-route.txt)
[ip-show.txt](https://github.com/vvviperrr/SimpleRT/files/6796229/ip-show.txt)

**Comment by tuxayo** [comment]
It doesn't work with app https://github.com/vvviperrr/SimpleRT/releases/tag/1.1

But it does work with this one!
https://github.com/iteratec/SimpleRT/releases/tag/v1.2.3

Should commits from this fork be integrated in this repo?

**Comment by robinpaulson** [comment]
@tuxayo I will be investigating commits from a few forks, including @iteratec and @candysunplus. If there are any in particular you would like to see added, please mention them.

**Comment by robinpaulson** [comment]
I put out a new version this week, at least #37 is now fixed.

**Comment by tuxayo** [comment]
@robinpaulson problem still there, with 1.1.1 from F-droid it doesn't ask me to use simple rt app for this usb accessory. 
Neither to allow it to work as a vpn app. It tells me no installed app is compatible with this USB accessory.

With this: https://github.com/iteratec/SimpleRT/releases/tag/v1.2.3 it works as expected.

PC counterpart version: 20211207_e9760dd (current master)

phone: Samsung Galaxy S4
OS Android 7 (LineageOS for microG 14.1)

**Comment by SSD2019** [comment]
Increasing the version number in the server version code fixed the issue for me.  This repo and the current 1.1 version in F-Droid.

diff --git a/simple-rt-cli/src/adk.c b/simple-rt-cli/src/adk.c
index 7631151..45b2b45 100644
--- a/simple-rt-cli/src/adk.c
+++ b/simple-rt-cli/src/adk.c
@@ -233,14 +233,14 @@ accessory_t *probe_usb_device(struct libusb_device *dev,
             .request_type = LIBUSB_ENDPOINT_OUT | LIBUSB_REQUEST_TYPE_VENDOR,
             .bRequest = AOA_SEND_IDENT,
             .wIndex = AOA_STRING_VER_ID,
-            .data = "1.0",
+            .data = "1.1",
         },
         {
             .str = "url",
             .request_type = LIBUSB_ENDPOINT_OUT | LIBUSB_REQUEST_TYPE_VENDOR,
             .bRequest = AOA_SEND_IDENT,
             .wIndex = AOA_STRING_URL_ID,
-            .data = "https://github.com/vvviperrr/SimpleRT",
+            .data = "https://github.com/robinpaulson/SimpleRT",
         },
         {
             .str = "serial number",
